# Generated by Django 4.2.11 on 2024-04-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kerasmodel',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả'),
        ),
    ]
